name = "ITensorQuantumOperatorDefinitions"
uuid = "fd9b415b-e710-4e2a-b407-cba023081494"
authors = ["ITensor developers <support@itensor.org> and contributors"]
version = "0.1.0"

[compat]
julia = "1.10"
