name = "ITensorQuantumOperatorDefinitions"
uuid = "fd9b415b-e710-4e2a-b407-cba023081494"
authors = ["ITensor developers <support@itensor.org> and contributors"]
version = "0.1.2"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1.10"
julia = "1.10"
