name = "QuantumOperatorDefinitions"
uuid = "826dd319-6fd5-459a-a990-3a4f214664bf"
authors = ["ITensor developers <support@itensor.org> and contributors"]
version = "0.1.3"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[weakdeps]
ITensorBase = "4795dd04-0d67-49bb-8f44-b89c448a1dc7"

[extensions]
QuantumOperatorDefinitionsITensorBaseExt = "ITensorBase"

[compat]
ITensorBase = "0.1.10"
LinearAlgebra = "1.10"
Random = "1.10"
julia = "1.10"
